export const portalCopy = {
  nav: {
    signup: 'Create member account',
    login: 'Sign in',
    portal: 'Member space',
    logout: 'Sign out',
  },
  landing: {
    title: 'Welcome to your private SheGymZ space',
    subtitle: 'Access your schedule, bookings, and member-only SheGymZ experience.',
    primaryCta: 'Sign in',
    secondaryCta: 'Create member account',
    helper: 'Already subscribed? Use the same email you used when joining SheGymZ.',
  },
  signup: {
    title: 'Create your member account',
    subtitle:
      "Use the email you joined SheGymZ with. We'll confirm your membership and send you a secure code.",
    emailLabel: 'Membership email',
    continueCta: 'Continue',
    loading: 'Confirming your membership...',
    noMembershipTitle: "We couldn't find an active SheGymZ membership for this email.",
    noMembershipBody: 'Please use the email you used when subscribing, or return to SheGymZ to join.',
    tryAnotherEmail: 'Try another email',
    goToSheGymZ: 'Go to SheGymZ',
    codeTitle: 'Check your email',
    codeSubtitle: 'We sent you a secure code. Enter it below to continue.',
    codeLabel: 'Secure code',
    verifyCodeCta: 'Verify code',
    resendText: "Didn't receive it? Send a new code.",
    successText: "You're verified. Let's finish setting up your member account.",
  },
  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to access your SheGymZ member space.',
    googleButton: 'Continue with Google',
    emailButton: 'Sign in with email',
    error: 'Those details did not match. Please try again.',
  },
  dashboard: {
    title: 'Your SheGymZ space',
    subtitle:
      'Book your sessions, check your schedule, and stay connected to your private wellness space.',
    schedulerTitle: 'Mina Scheduler',
    schedulerDescription: 'Manage your sessions and stay up to date with your SheGymZ schedule.',
    schedulerCta: 'Open Scheduler',
    membershipTitle: 'Membership',
    membershipDescription: 'Your active membership gives you access to the SheGymZ member portal.',
    statusLabel: 'Active',
  },
  locked: {
    title: 'Your membership needs attention',
    body: 'This member space is available to active SheGymZ members. Please check your subscription or contact SheGymZ for support.',
    returnToSheGymZ: 'Return to SheGymZ',
    tryAgain: 'Try again',
  },
  safeErrors: {
    default: 'Something did not go through. Please try again in a moment.',
    credentials: 'Those details did not match. Please try again.',
    code: 'That secure code did not match. Please try again.',
    expired: 'That secure code has expired. Please request a new one.',
    accountExists: 'A member account already exists for this email. Please sign in instead.',
    passwordMismatch: 'Those passwords do not match. Please try again.',
    passwordInvalid: 'Please enter your name and choose a password with at least 8 characters.',
  },
  external: {
    shegymzUrl: 'https://shegymz.com',
  },
} as const;
