export const portalCopy = {
  nav: {
    signup: 'Create member account',
    login: 'Sign in',
    portal: 'Access your space',
    logout: 'Sign out',
  },
  chrome: {
    privateLabel: 'Private member space',
    wellbeingLabel: "SheGymZ women's wellness club",
  },
  landing: {
    title: 'Welcome to your private SheGymZ space',
    subtitle: 'Access your schedule, bookings, and member-only SheGymZ experience.',
    primaryCta: 'Sign in',
    secondaryCta: 'Create member account',
    helper: 'Already subscribed? Use the same email you used when subscribing to SheGymZ.',
    featureEyebrow: 'Private women\'s wellness club',
    featureTitle: 'A private member space for the work you are doing for yourself.',
    featureLabel: 'Safe. Soft. Strong.',
  },
  signup: {
    title: 'Create your member account',
    subtitle:
      "Use the email you subscribed to SheGymZ with. We'll confirm your membership and send you a secure code.",
    emailLabel: 'Membership email',
    continueCta: 'Continue',
    loading: 'Confirming your membership...',
    noMembershipTitle: "We couldn't find an active SheGymZ membership for this email.",
    noMembershipBody: 'Please use the email you used when subscribing, or return to SheGymZ to join.',
    tryAnotherEmail: 'Try another email',
    goToSheGymZ: 'Go to SheGymZ',
    codeTitle: 'Check your email',
    codeSubtitle: 'We sent you a secure code. Enter it below to continue.',
    codeLabel: 'Secure code',
    verifyCodeCta: 'Verify code',
    resendText: "Didn't receive it? Send a new code.",
    successText: "You're verified. Let's finish setting up your member account.",
    signInInstead: 'Already set up? Use member sign-in instead.',
    stepEmail: 'Share the email you used when subscribing to SheGymZ.',
    stepCode: 'Enter the secure code we send to your inbox.',
    stepFinish: 'Finish your member account with a password or Google.',
    codeSentMessage: 'We sent a secure code to {email}. It expires in {minutes} minutes.',
    verifyLoading: 'Checking your code...',
    accountConnectedPrefix: 'Your account will be connected to',
    fullNameLabel: 'Full name',
    fullNamePlaceholder: 'Your name',
    passwordLabel: 'Create password',
    passwordPlaceholder: 'At least 8 characters',
    confirmPasswordLabel: 'Confirm password',
    confirmPasswordPlaceholder: 'Repeat password',
    createPasswordCta: 'Create account with password',
    createAccountLoading: 'Creating your account...',
    googleFinishCta: 'Continue with Google',
    googleHintPrefix: 'For your privacy, use the Google account connected to',
    accountReadyMessage: 'Your member account is ready for {email}. You can sign in now.',
  },
  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to access your SheGymZ member space.',
    googleButton: 'Continue with Google',
    emailButton: 'Sign in with email',
    error: 'Those details did not match. Please try again.',
    loading: 'Signing you in...',
    helper: 'New to the portal?',
  },
  dashboard: {
    title: 'Your SheGymZ space',
    subtitle:
      'Book your sessions, check your schedule, and stay connected to your private wellness space.',
    schedulerTitle: 'Mina Scheduler',
    schedulerDescription: 'Manage your sessions and stay up to date with your SheGymZ schedule.',
    schedulerCta: 'Open Scheduler',
    membershipTitle: 'Membership',
    membershipDescription: 'Your active membership gives you access to the SheGymZ member portal.',
    statusLabel: 'Active',
    signedInAs: 'Signed in as',
    memberHomeLabel: 'Member home',
    atmosphereTitle: 'Private, calm access to your SheGymZ rhythm.',
    bookingsLabel: 'Bookings',
    membershipPill: 'Active membership',
  },
  locked: {
    title: 'Your membership needs attention',
    body: 'This member space is available to active SheGymZ members. Please check your subscription or contact SheGymZ for support.',
    returnToSheGymZ: 'Return to SheGymZ',
    tryAgain: 'Try again',
    privateAccessLabel: 'Private member access',
    privateAccessTitle: 'Your space is here when your membership is active.',
  },
  schedule: {
    eyebrow: 'Mina Scheduler',
    title: 'Make space for yourself.',
    subtitle: 'Manage your sessions and stay up to date with your SheGymZ schedule.',
    backCta: 'Back to your SheGymZ space',
    rhythmLabel: 'Your rhythm',
    rhythmTitle: 'Plan your sessions with a little more ease and a lot more intention.',
  },
  safeErrors: {
    default: 'Something did not go through. Please try again in a moment.',
    credentials: 'Those details did not match. Please try again.',
    code: 'That secure code did not match. Please try again.',
    expired: 'That secure code has expired. Please request a new one.',
    accountExists: 'A member account already exists for this email. Please sign in instead.',
    passwordMismatch: 'Those passwords do not match. Please try again.',
    passwordInvalid: 'Please enter your name and choose a password with at least 8 characters.',
    requestCode: 'We could not send your secure code just now. Please try again.',
    createAccount: 'We could not create your member account just now. Please try again.',
  },
  external: {
    shegymzUrl: 'https://shegymz.com',
  },
} as const;
